version: '3.4'
networks:
  group4:
volumes:
  group4-keycloak-data:
    external: true
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - group4-keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - group4
    
  oauth-service:
    container_name: oauth-service
    build: .
    image: leoberlatto/oauth-service:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=group4
      - KEYCLOAK_CLIENT_SECRET=9f9b9b5e-9b9b-5e9f-9b9b-5e9f9b9b5e9b
    networks:
      - group4
