spring:
  application:
    name: oauth-service

  security:
    oauth2:
      keycloak:
        realm:
          name: ${KEYCLOAK_REALM:construcao-sw}
          url: ${KEYCLOAK_REALM_URL:http://localhost:8090}/realms/construcao-sw/
          admin-url: ${KEYCLOAK_REALM_URL:http://localhost:8090}/admin/realms/construcao-sw/

management:
  endpoints:
    web:
      exposure:
        include: [health, info, env, metrics]