apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-service
  name: keycloak-service
spec:
  ports:
    - name: "8090"
      port: 8080
      targetPort: 8090
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}
