apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace: cs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start-dev
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: a12345678
            - name: KEYCLOAK_FRONTEND_URL
              value: http://${KEYCLOAK_SERVICE_IP}:8080
          image: quay.io/keycloak/keycloak:21.0.2
          name: keycloak
          ports:
            - containerPort: 8080
      restartPolicy: Always
