apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: oauth
  name: oauth
  namespace: cs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oauth
  template:
    metadata:
      labels:
        io.kompose.service: oauth
    spec:
      containers:
        - env:
            - name: KEYCLOAK_CLIENT_ID
              value: oauth
            - name: KEYCLOAK_CLIENT_SECRET
              value: 04bfUatIDO6ipwg1TF2mTzHrX8UZD02Z
            - name: KEYCLOAK_REALM
              value: construcao-sw
            - name: KEYCLOAK_REALM_URL
              value: http://${KEYCLOAK_SERVICE_IP}:8090
          image: ghcr.io/constr-sw-2023-1/oauth-g4:main
          name: oauth
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret

