name: Deploy to OKE

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]
    branches:
      - main
    
jobs:
  install-kubectl:
    runs-on: ubuntu-latest
    name: Deploy to OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Connect to OKE Cluster
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Deploy on Kubernetes
        run: 
          kubectl create secret docker-registry GHCR_SECRET --docker-server=https://ghcr.io --docker-username=HBO1705 --docker-password=${{ secrets.IMAGE_ACCESS_TOKEN }} --docker-email=h.oliveira@edu.pucrs.br
          kubectl apply -f oauth-g4-group4-networkpolicy.yaml
          kubectl apply -f oauth-service-deployment.yaml
          kubectl apply -f oauth-service-service.yaml
        
  
