name: Deploy to OKE

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to OKE Cluster
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
          
      - name: Deploy on Kubernetes
        run: |
          kubectl apply -f .
        working-directory: ${{ github.workspace }}/k8s
